# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(help_text='A person who buys something', max_length=200)),
                ('quantity', models.IntegerField(help_text='A large quantity of goods bought at one time')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], help_text='Classification of the status of a purchase', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(help_text='The status model related with purchase model', on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseModel')),
            ],
        ),
    ]
