# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-11 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestatusmodel',
            name='purchase',
            field=models.ForeignKey(help_text='The status model related with purchase model', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_status', to='purchase.PurchaseModel'),
        ),
    ]
