# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200911_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestatusmodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
